name: Python Flask CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.11'  # Versão do Python que você está usando

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest tests/

    - name: Lint with flake8
      run: |
        source venv/bin/activate
        pip install flake8
        flake8 app tests

    - name: Run Flask app
      run: |
        source venv/bin/activate
        python run.py
      env:
        FLASK_ENV: development
